name: Build on Self-Hosted Runner

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ self-hosted, arm64 ]
    steps:
      - uses: actions/checkout@v3
      - name: Print info
        run: uname -a
