name: Build on Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # self-hosted Runner (ARM64) が動いていることをテストするだけ
    runs-on: [ self-hosted, ARM64 ]

    steps:
      # 何かリポジトリのファイルが必要であればcheckout
      - uses: actions/checkout@v3

      - name: Test Command
        run: |
          echo "Hello from Raspberry Pi self-hosted runner!"
          uname -a
          # ここで適宜テスト用のコマンドを追加
