name: Update STM32 Firmware

on:
  push:
    branches:
      - main
    paths:
      - "firmware/*.bin"

jobs:
  update-firmware:
    runs-on: self-hosted  # Raspberry Pi の self-hosted runner で実行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y stm32flash python3-gpiozero python3-serial

      - name: Run firmware updater
        run: |
          BIN_FILE=$(ls firmware/*.bin | head -n 1)
          echo "Using firmware: $BIN_FILE"
          python3 updater.py --bin "$BIN_FILE" --device /dev/ttyAMA0 --baudrate 115200
